In [8]:
import timeit                                   # Used in timer_function to test code execution times
import numpy as np                              # Numerical processing library
import matplotlib.pyplot as plt                 # Matplotlib plotting library
from functools import partial

###Helper functions 
def drag_race(number, repeats, functions, args_lists, sig_figs=3, share_args=False):
    """
    Runs timeit.repeat on each function in the the input list 'functions' a specified number of times and 
    prints the minimum runtime for each func
    
    # Arguments:
    number:     Number of times to run the functions per repeat.
    repeats:    Number of times to time the function (each time function is timed it is run 'number' times).
    functions:  The functions to be timed, in format [function_name_1, function_name_2].
    args_lists: Arguments to pass to the functions using format [[F1-arg1, F1-arg2], [F2-arg1, F2-arg2, F2-arg3]] Unless all 
                functions take same arguments in which case pass [[shared_arg1, shared_arg2]] and then also set share_args=True.
    sig_figs:   Sets the number of significant figures for the printed results readout [Default=3].
    share_args: If all functions share the same argumnets then passing share_args=True allows user to only input them once and they are used for all fucntions [Default=False].
    
    # Returns:
    No values are returned instead function automatically prints statment with function names and min runtimes.
    """
    
    if share_args == True:
        args_lists = args_lists * len(functions)  # If share args is used the single set of arguments is copied for the numebr of function requiring them
        
    for i, function in enumerate(functions):
        function_partial = partial(function, *args_lists[i])
        run_times = timeit.repeat(function_partial, number=number, repeat=repeats)
        min_time = min(run_times)/number

        print("\nFunction: {}\nRuntime: {} ms (minimum result over {} runs)".format(function.__name__, round(min_time*1000, sig_figs), repeats))

In [9]:
### update to use csr_matrix sparse matrix format
import numpy as np
from scipy.sparse import coo_matrix


In [10]:
def create_grid_with_coordinates(coordinates, grid_shape):
    grid = np.zeros(grid_shape, dtype=int)

    for coord in coordinates:
        x, y = coord
        grid[y, x] = 1

    return grid

def create_sparse_grid_with_coordinates(coordinates, grid_shape):
    y_coords, x_coords = zip(*coordinates)
    data = np.ones(len(coordinates), dtype=int)
    grid = coo_matrix((data, (y_coords, x_coords)), shape=grid_shape)
    return grid

# Example usage
coordinates_list = [(0, 0), (1, 1), (2, 2), (3, 4), (4, 3), (4, 4), (4, 0), (4, 1), (4, 2), (0, 4), (1, 4), (2, 4), (3, 0), (3, 1), (3, 2), (3, 3), (0, 3), (1, 3), (2, 3), (0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1), ]
grid_shape = (5, 5)  # Example shape, replace with your own dimensions




In [11]:
functions = [create_grid_with_coordinates, create_sparse_grid_with_coordinates]
args_lists = [[coordinates_list, grid_shape]]
drag_race(1000, 1000, functions, args_lists, sig_figs=3, share_args=True)


Function: create_grid_with_coordinates
Runtime: 0.001 ms (minimum result over 1000 runs)

Function: create_sparse_grid_with_coordinates
Runtime: 0.028 ms (minimum result over 1000 runs)


In [12]:

grid_array = create_grid_with_coordinates(coordinates_list, grid_shape)
print(grid_array)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]]


In [13]:
sparse_grid = create_sparse_grid_with_coordinates(coordinates_list, grid_shape)
print(sparse_grid.toarray())

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [14]:



def extract_coordinates_from_grid(grid):
    coordinates = []

    for y, row in enumerate(grid):
        for x, value in enumerate(row):
            if value == 1:
                coordinates.append((x, y))

    return coordinates

coordinates = extract_coordinates_from_grid(grid_array)
print(coordinates)


[(0, 0), (1, 1), (2, 2), (3, 4)]
