In [1]:
import torch#

indices = torch.tensor([[0, 1], [1, 2]])
values = torch.tensor([3.0, 4.0])
sparse_tensor = torch.sparse_coo_tensor(indices, values, size=(2, 3))

print(sparse_tensor)

tensor(indices=tensor([[0, 1],
                       [1, 2]]),
       values=tensor([3., 4.]),
       size=(2, 3), nnz=2, layout=torch.sparse_coo)


In [13]:

torch.manual_seed(10)

dense_tensor = torch.zeros(1, 1, 3, 3)
dense_tensor[0, 0, 0, 0] = 1
dense_tensor[0, 0, 1, 1] = 1
dense_tensor[0, 0, 2, 2] = 1

print(dense_tensor.shape)
print(dense_tensor)



torch.Size([1, 1, 3, 3])
tensor([[[[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]]]])


In [31]:
sparse_tensor = dense_tensor.to_sparse_coo()

print(sparse_tensor.shape)
print(sparse_tensor)

torch.Size([1, 1, 3, 3])
tensor(indices=tensor([[0, 0, 0],
                       [0, 0, 0],
                       [0, 1, 2],
                       [0, 1, 2]]),
       values=tensor([1., 1., 1.]),
       size=(1, 1, 3, 3), nnz=3, layout=torch.sparse_coo)


In [32]:
print(sparse_tensor.indices())
print(sparse_tensor.values())

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 1, 2],
        [0, 1, 2]])
tensor([1., 1., 1.])


In [33]:
THREEDEE = torch.zeros(1, 1, 3, 3, 10)
print(THREEDEE)

tensor([[[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]]])


In [34]:
THREEDEE = THREEDEE.scatter(2, sparse_tensor.indices(), 1.0)


RuntimeError: Index tensor must have the same number of dimensions as self tensor

In [37]:
import torch

# Create a sparse matrix (COO format)
indices = torch.tensor([[0, 1, 1, 2],
                        [1, 0, 2, 1]])
values = torch.tensor([2, 3, 4, 5])
sparse_matrix = torch.sparse_coo_tensor(indices, values, (3, 3))

# Convert the sparse matrix to a dense tensor
dense_matrix = sparse_matrix.to_dense()

# Get indices and values from the sparse matrix
sparse_indices = sparse_matrix.coalesce().indices()
sparse_values = sparse_matrix.coalesce().values()

# Perform scatter operation using torch_scatter.scatter
num_nodes = 3
output = torch.zeros(num_nodes, dtype=torch.int64)
output.scatter(sparse_values, sparse_indices[0], out=output, dim_size=num_nodes, reduce='add')

print("Original dense matrix:")
print(dense_matrix)
print("Output after scatter operation:")
print(output)


TypeError: scatter() received an invalid combination of arguments - got (Tensor, Tensor, reduce=str, out=Tensor, dim_size=int), but expected one of:
 * (int dim, Tensor index, Tensor src)
 * (int dim, Tensor index, Tensor src, *, str reduce)
      didn't match because some of the keywords were incorrect: out, dim_size
 * (name dim, Tensor index, Tensor src)
 * (int dim, Tensor index, Number value)
 * (int dim, Tensor index, Number value, *, str reduce)
      didn't match because some of the keywords were incorrect: out, dim_size
 * (name dim, Tensor index, Number value)
