In [9]:
import torch
import numpy as np


print(torch.initial_seed())
print(np.random.get_state()[1][0])


print(torch.rand(3, 3))
print(np.random.rand(3, 3))

print(torch.initial_seed())
print(np.random.get_state()[1][0])

6
1238707723
tensor([[0.1674, 0.3333, 0.4648],
        [0.6332, 0.7692, 0.2147],
        [0.7815, 0.8644, 0.6052]])
[[0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551 ]
 [0.99022427 0.8198582  0.41320093]]
6
1238707723


In [10]:
seeding_value = 6


In [11]:
# Helper fucntion that sets RNG Seeding for determinism in debugging
def Determinism_Seeding(seed):
    torch.manual_seed(seed)
    np.random.seed(seed)

# Initialises seeding values to RNGs
if seeding_value:
    Determinism_Seeding(seeding_value)             # Set the seed for the RNGs
    print("Seeding with value:", seeding_value)
else:
    torch.seed()                                    # Set the seed for the RNGs
    np.random.seed()

T_seed = torch.initial_seed()
N_seed = np.random.get_state()[1][0]


Seeding with value: 6


In [12]:

print(np.random.get_state()[1][0])
print(torch.initial_seed())

print(torch.rand(3, 3))
print(np.random.rand(3, 3))

6
6
tensor([[0.5722, 0.5539, 0.9868],
        [0.6080, 0.2347, 0.4492],
        [0.6743, 0.7480, 0.5601]])
[[0.89286015 0.33197981 0.82122912]
 [0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785]]
